if(NOT PROJECT_ENABLE_TESTING AND NOT PROJECT_ENABLE_BENCHMARKS AND NOT PROJECT_ENABLE_SPDLOG)
  return()
endif()

include("${CMAKE_CURRENT_LIST_DIR}/../CPM.cmake")

if(PROJECT_ENABLE_TESTING)
  if(CMAKE_CXX_STANDARD LESS 17)
    # GoogleTest 1.18 requires C++17; 1.12.1 supports C++14 projects.
    set(PROJECT_GOOGLETEST_VERSION 1.12.1)
    set(PROJECT_GOOGLETEST_TAG release-1.12.1)
  else()
    set(PROJECT_GOOGLETEST_VERSION 1.18.0)
    set(PROJECT_GOOGLETEST_TAG v1.18.0)
  endif()

  CPMAddPackage(
    NAME googletest
    GITHUB_REPOSITORY google/googletest
    VERSION ${PROJECT_GOOGLETEST_VERSION}
    GIT_TAG ${PROJECT_GOOGLETEST_TAG}
    OPTIONS "INSTALL_GTEST OFF" "gtest_force_shared_crt ON"
  )
endif()

if(PROJECT_ENABLE_BENCHMARKS)
  CPMAddPackage(
    NAME benchmark
    GITHUB_REPOSITORY google/benchmark
    VERSION 1.9.5
    OPTIONS "BENCHMARK_ENABLE_TESTING OFF" "BENCHMARK_ENABLE_INSTALL OFF"
  )
endif()

if(PROJECT_ENABLE_SPDLOG)
  CPMAddPackage(
    NAME spdlog
    GITHUB_REPOSITORY gabime/spdlog
    VERSION 1.17.0
    OPTIONS "SPDLOG_BUILD_EXAMPLE OFF" "SPDLOG_BUILD_TESTS OFF" "SPDLOG_INSTALL OFF"
  )
endif()
